# 📌1.1 머신러닝의 개념

### **머신러닝**: 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

기존에 존재하던 복잡한 소스코드들의 문제를 해결
- 지도학습(분류, 회귀, 추천 시스템, 시각/음성 감지/인지, 텍스트 분석 NLP)
- 비지도학습(클러스터링, 차원 축소)
- 강화학습  

데이터에 매우 의존적 ->좋은 품질의 데이터를 갖추는 것이 중요

### R VS Python?
| R | Python |
| ------------ | ------------- |
| 통계 전용 | 개발용 -> 여기저기 다 쓰임 |
| 다수의 통계 패키지 | 다수의 딥러닝 패키지 |  

굳이 비교하자면 이렇고, 파이썬이 전반적으로 더 많이 사용되고 오픈된 패키지가 많음.  
 -> 여기선 파이썬을 쓰자~


# 📌1.2 파이썬 머신러닝 생태계를 구성하는 주요 패키지

머신러닝 -> 사이킷런(sklearn), 텐서플로(tensorflow), 케라스(keras)  
행렬/선형대수/통계 -> Numpy, Scipy  
데이터 핸들링 -> Pandas  
시각화(그래프) -> matplotlib, seaborn


구글 코랩 사용으로 교재 p.7~12 내용은 생략했습니다.

# 📌1.3 넘파이

Numerical Python  , 선형대수 기반의 프로그램 지원 패키지


### 넘파이 ndarray 개요

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 2, 3])
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape)

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


In [3]:
#문자열 포맷팅 이용, 위에서 생성한 array 차원 확인
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,
                                                              array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


- `array`
 - ndarray 생성
 - [] 대괄호의 수 -> ndarray의 차원
- `shape`
 - ndarray의 크기를 튜플 형태로 반환
- `ndim`
 - ndarray의 차원 수 반환


### ndarray의 데이터 타입

In [4]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


 *교재에선 int32라고 되어있지만 여기선 64로 되어있어서 찾아보니,  
 둘의 차이는 표현가능한 숫자의 범위.  
 (ex. int 32 -> 2^32개의 정수 표현 가능)

In [5]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [8]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.astype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] <built-in method astype of numpy.ndarray object at 0x7f8d052424f0>
[1 2 3] int32
[1 2 3] int32


- `type`
 - ndarray 그 자체의 타입 반환
 - 그래서 ndarray에 쓰면 당연히 ndarray라고 반환값 나옴  
- `dtype`
 - ndarray 내부의 데이터 타입 반환  
- `astype`
 - 특정 데이터 타입으로의 변경  
 - ex) float --astype('int32')--> int32 (소수점 아래 다 떨어짐)

*데이터 타입이 섞여있는 경우 데이터 타입이 더 큰 데이터 타입으로 변환되어 사용됨.  
-> 그냥 다른 데이터 타입도 표현 가능한 타입이 더 크다고 생각하면 쉬움,  
따라서 데이터 타입이 작을 수록 메모리 절약이 가능함  
-> str > float > int

### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [10]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [12]:
zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


- `arange(n)`
 - 0부터 (n-1)까지의 수를 1씩 늘려가며 ndarray의 데이터값으로 변환
 - 함수 인자로 start, stop 값을 지정 가능. (하나만 넣으면 stop 값이라고 인식)  
 => arange(a, b) : a부터 (b-1)값까지
 -파이썬 내장함수 `range()`와 유사

- `zeros(a, b)`
 - a행 b열 크기의 모든 element가 0인 ndarray 생성
 - 기본적으로 dtype은 int32

- `ones(a, b)`
 - a행 b열 크기의 모든 element가 1인 ndarray 생성
 - 기본적으로 dtype이 float64, 함수에 인자로 dtype = ''를 넣어서 dtype 지정 가능



### ndarray의 차원과 크기를 변경하는 reshape()

In [13]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
array1.reshape(4, 3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [15]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape: ', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape: ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)
array3 shape:  (5, 2)


In [16]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [17]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape: ', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape: ', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:  (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:  (8, 1)


- `reshape(a, b)`
 - 기존의 ndarray를 a행, b열 shape의 ndarray로 변경
 - n개의 element가 있을 때 a 혹은 b가 n의 약수가 아니라면 에러가 남.  
~당연함. 10개짜리를 어떻게 4*2.5크기로 바꿈? 2.5열? 당연히 안됨.~
 - `reshape(a, -1)`, `reshape(-1, b)`  
   -> element가 n개일 때 각각 a행, (n/a)열 크기의 ndarray, (n/b)행, b열 크기의 ndarray가 됨.
 -reshape를 사용하면 무조건 2차원의 ndarray가 됨.


### 넘파이의 ndarray 데이터 세트 선택하기 - 인덱싱(indexing)

**인덱싱**: ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택  

#### 특정한 데이터만 추출: 원하는 위치의 인덱스 값 지정  

In [18]:
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start = 1, stop = 10)
print('array1: ', array1)
#index는 0부터 시작하므로 array1[2]는 3번쩨 index 위치의 데이터값을 의미
value = array1[2]
print('value: ', value)
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int64'>


In [19]:
print('맨 뒤의 값: ',array1[-1], '맨 뒤에서 두 번째 값: ', array1[-2])

맨 뒤의 값:  9 맨 뒤에서 두 번째 값:  8


In [20]:
array1[0] = 9
array1[8] = 0
print('array1: ', array1)

array1:  [9 2 3 4 5 6 7 8 0]


In [21]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row = 0, col = 0) index 가리키는 값: ', array2d[0, 0])
print('(row = 0, col = 1) index 가리키는 값: ', array2d[0, 1])
print('(row = 1, col = 0) index 가리키는 값: ', array2d[1, 0])
print('(row = 2, col = 2) index 가리키는 값: ', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row = 0, col = 0) index 가리키는 값:  1
(row = 0, col = 1) index 가리키는 값:  2
(row = 1, col = 0) index 가리키는 값:  4
(row = 2, col = 2) index 가리키는 값:  9


**파이썬의 인덱스는 0부터 시작**  
-> 첫번째 원소를 추출하려면 0을 사용해야함.  
`ndarray[a]` -> 앞에서 (a+1)번째 원소  
`ndarray[-a]` -> 뒤에서 a번째 원소  
`ndarray[a, b]` -> (a+1)번쩨 행, (b+1)번째 열의 원소.    



#### 슬라이싱: ':'을 통해 연속된 인덱스 상의 ndarray 추출  


In [22]:
array1 = np.arange(start = 1, stop = 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [23]:
array1 = np.arange(start = 1, stop = 10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [24]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [25]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape: ', array2d[0].shape, 'array2d[1] shape: ', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape:  (3,) array2d[1] shape:  (3,)


`ndarray[a:b]` -> (a+1)번쩨 원소부터 b번째 원소까지.(a<b)  
`ndarray[a:-1]` -> (a+1)번쩨 원소부터 마지막 원소까지.   
`ndarray[a:]` -> (a+1)번쩨 원소부터 마지막 원소까지.  
`ndarray[:b]` ->첫번째 원소부터 b번째 원소까지.  
`ndarray[:]` -> 전체 원소

#### 팬시 인덱싱: 일정한 인덱싱 집합으로 위치 지정  

In [26]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] => ', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] => ', array5.tolist())

array2d[[0, 1], 2] =>  [3, 6]
array2d[[0, 1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0, 1]] =>  [[1, 2, 3], [4, 5, 6]]


위의 슬라이싱과 유사, 슬라이싱을 2차원 ndarray에 사용하는 거랑 비슷함.

#### 불린 인덱싱: 조건따라 추출

In [27]:
array1d = np.arange(start = 1, stop = 10)
#[]안에 array1d>5 Boolean indexing을 적용
array3 = array1d[array1d>5]
print('array1d>5 불린 인덱싱 결과 값: ', array3)

array1d>5 불린 인덱싱 결과 값:  [6 7 8 9]


In [28]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [29]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과: ', array3)

불린 인덱스로 필터링 결과:  [6 7 8 9]


In [30]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과: ', array4)

일반 인덱스로 필터링 결과:  [6 7 8 9]


- `ndarray[조건]`  
 - 조건문에서 True를 반환하는 인덱스에 해당하는 element들을 반환  
 - for loop 와 같이 반복문을 사용하지 않고도 조건 필터링 가능.

### 행렬의 정렬 - sort(), argsort()

In [32]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬: ', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 원본 행렬: ', org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 정렬 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬: ', org_array)

원본 행렬:  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]
org_array.sort() 호출 후 반환된 정렬 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]


In [33]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬: ', sort_array1_desc)

내림차순으로 정렬:  [9 5 3 1]


In [34]:
array2d = np.array([[8, 12],
                    [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('칼럼 방향으로 정렬: \n', sort_array2d_axis1)

로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


In [35]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


In [36]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스: ', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스:  [2 3 0 1]


In [37]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스: ', sort_indices_asc)
print('성적 오름차순으로  name_array의 이름 출력: ', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스:  [0 2 4 1 3]
성적 오름차순으로  name_array의 이름 출력:  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


|기존 행렬|기존 인덱스| => |정렬 후 행렬|정렬 후 인덱스|
|----|----|----|----|----|
|78|0| => |78|0|
|95|1| => |84|2|
|84|2| => |88|4|
|98|3| => |95|1|
|88|4| => |98|3|

- `np.sort(ndarray, axis = 0)`
 - 원본 행렬 변경 없이 정렬된 형태 반환,  
 - axis = 0 -> 로우 방향으로 정렬  
 - axis = 1 -> 칼럼 방향으로 정렬   
  
- `ndarray.sort()`
 - 반환값 없이 원본 행렬 자체를 정렬한 상태로 변경  
 - 정렬은 모두 오름차순 정렬. 내림차순으로 정렬하기 위해선 [::-1]로 인덱싱  
  
- `argsort()`
 - 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환. (이해가 어려우면 위의 예시 참고)  
 - 내림차순 적용할 시엔 argsort(ndarray)[::-1]

### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [39]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [40]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬: \n', transpose_mat)

A의 전치 행렬: 
 [[1 3]
 [2 4]]


행렬내적 -> np.dot(A, B)
: A, B의 행렬 내적을 반환  
전치행렬 -> np.transpose(A)
: A의 전치 행렬 반환