<a href="https://colab.research.google.com/github/whyeon92/ESAA_YB/blob/Online_Quiz/ESAA_Online_Quiz0311.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.25.2


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
v3 = np.zeros(10)
v3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
v3.nbytes

80

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [5]:
v1 = np.zeros(10)
v1[4] = 1
v1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [6]:
v2 = np.arange(10, 50)
v2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
v3 = np.zeros(40)
for i in range(40):
  v3[i] = v2[-i-1]

v3

array([49., 48., 47., 46., 45., 44., 43., 42., 41., 40., 39., 38., 37.,
       36., 35., 34., 33., 32., 31., 30., 29., 28., 27., 26., 25., 24.,
       23., 22., 21., 20., 19., 18., 17., 16., 15., 14., 13., 12., 11.,
       10.])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
v8 = np.arange(9)
v8.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
v9 = np.array([1,2,0,0,4,0])
np.nonzero(v9)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [10]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [11]:
v11 = np.random.random([3, 3, 3])
v11

array([[[0.80402359, 0.65274995, 0.86335165],
        [0.78782243, 0.0484597 , 0.22133875],
        [0.03307332, 0.47797228, 0.03603656]],

       [[0.14049243, 0.28281165, 0.63652558],
        [0.42508476, 0.16960697, 0.66700889],
        [0.26360239, 0.05338067, 0.21595285]],

       [[0.62230329, 0.03940112, 0.76779121],
        [0.70425778, 0.79352491, 0.43183791],
        [0.72585947, 0.92158355, 0.16136915]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [12]:
m12 = np.random.random([10, 10])
m12
print(np.min(m12))
print(np.max(m12))

0.0010750340636678235
0.9931677655757181


#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [13]:
v13 = np.random.random(30)
np.mean(v13)

0.46149485410908553

#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [14]:
v14 = np.ones([4, 4])
v14[1:3, 1:3] = 0
v14

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [15]:
#nan
#False
#False
#nan
#True
#False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [16]:
np.diag([1, 2, 3, 4], k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
m17 = np.ones([8, 8])
m17[::2, ::2] = 0  #홀수 열, 홀수 행 -> 0
m17[1::2, 1::2] = 0  #짝수 열, 짝수 행 -> 0
m17

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [18]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [19]:
m19 = np.random.random((5, 5))
m19 = (m19 - m19.mean()) / m19.std()
m19

array([[ 0.68042587, -0.88553005, -1.138116  , -0.21648051,  0.04457226],
       [ 0.85102289, -0.55549413,  0.46819901, -1.30686894, -0.8006342 ],
       [-0.71146585,  0.70988561,  1.83863466,  1.93191787,  0.06434868],
       [-1.55965348, -1.34612745, -0.11362633,  1.36459718, -0.90078981],
       [ 0.7005408 , -0.7323989 ,  1.64594316, -0.09624617,  0.06334382]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [20]:
v20 = np.dtype([('red', np.ubyte), ('green', np.ubyte), ('blue', np.ubyte), ('alpha', np.ubyte)])
print(v20)

[('red', 'u1'), ('green', 'u1'), ('blue', 'u1'), ('alpha', 'u1')]


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [21]:
m211 = np.random.random((5, 3))
m212 = np.random.random((3, 2))

m211@m212

array([[0.98177353, 0.44912559],
       [0.90099004, 0.47595221],
       [0.35560526, 0.2890869 ],
       [0.52703786, 0.50119659],
       [0.60808082, 0.40769752]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [22]:
v22 = np.arange(22)
v22[(v22<8) & (v22>3)] *= -1
v22

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [23]:
#9, 10

#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [24]:
Z = np.array([5, 5])
print()
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)


[3125 3125]
[16 16]
[False False]
[0.+5.j 0.+5.j]
[5. 5.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [25]:
#Z<Z>Z  <- 이것만 illegal

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:
#nan
#0
#array([-9.22337204e+18])

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [27]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
np.intersect1d(Z1, Z2)

array([0, 2, 4, 6, 9])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [28]:
#False
#np.sqrt(-1) -> nan (음수가 들어가면 계산 불가하기 때문)
#np.emath.sqrt(-1) -> (복소수에 대한 제곱근 반환)

In [1]:
import numpy as np

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [32]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [34]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))
np.add(A, B, out = B)
np.negative(A, out = A)
np.divide(A, 2, out = A)
np.multiply(A, B, out = B)
B

array([[-0.39378164, -0.12121523, -0.41296316],
       [-0.62344885, -0.85547762, -0.09375322],
       [-0.12239113, -0.07273923, -0.02947149]])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [35]:
v30 = np.random.random(10)
print(v30 - v30%1)
print(v30//1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [36]:
v31 = np.zeros((5, 5))
for i in range(5):
  v31[:, i] += i

v31

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 32. Create a random vector of size 10 and sort it (★★☆)

In [38]:
Z = np.random.random(10)
Z.sort()
Z

array([0.20891763, 0.22596997, 0.33133633, 0.36520396, 0.81298908,
       0.82255232, 0.83607608, 0.85841346, 0.90517129, 0.94191328])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [39]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.array_equal(A, B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [3]:
Z = np.random.random((10, 2))
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.98326797 0.19532085 0.78684262 0.88676868 0.77271267 1.16605122
 0.63347608 0.8968535  0.56351033 1.16513878]
[0.47068528 0.65209947 0.39919667 0.16184696 1.24804071 0.652927
 1.31151082 0.2869146  0.90984988 0.72865235]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [41]:
Z = np.random.random(10)
print(Z)
Zi = Z.argmax()
Z[Zi] = 0
Z

[0.87835134 0.85824716 0.91820227 0.19176567 0.35762734 0.0566829
 0.16411149 0.06937948 0.4492543  0.15180465]


array([0.87835134, 0.85824716, 0.        , 0.19176567, 0.35762734,
       0.0566829 , 0.16411149, 0.06937948, 0.4492543 , 0.15180465])

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [53]:
Z = np.arange(100)
v = np.random.uniform(0,100)
dis =abs(Z - v).argmin()
Z[dis]

74

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [46]:
Z = np.arange(9).reshape(3,3)
for i, j in np.ndenumerate(Z):
  print(i, j)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [48]:
n =6
p = 5
Z = np.zeros((n,n))
#https://numpy.org/doc/stable/reference/generated/numpy.put.html    np.put 참고
np.put(Z, np.random.choice(range(n*n), p, replace = False), 2)
print(Z)

[[0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 2. 2.]
 [0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [54]:
Z = np.random.randint(0,10,(3,3))
Z

array([[8, 9, 7],
       [1, 9, 1],
       [7, 6, 2]])

In [57]:
# column 1
Z[Z[:, 0].argsort()]

array([[1, 9, 1],
       [7, 6, 2],
       [8, 9, 7]])

In [58]:
# column 2
Z[Z[:, 1].argsort()]

array([[7, 6, 2],
       [8, 9, 7],
       [1, 9, 1]])

In [59]:
# column 3
Z[Z[:, 2].argsort()]

array([[1, 9, 1],
       [7, 6, 2],
       [8, 9, 7]])