<a href="https://colab.research.google.com/github/whyeon92/ESAA_YB/blob/Code_Study/ESAA_HW0322.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📌2.1 사이킷런 소개와 특징

In [ ]:
#코랩 사용으로 설치과정 주석처리
#!pip install scikit-learn

In [1]:
#사이킷런 버전 출력
import sklearn

print(sklearn.__version__)

1.2.2


[사이킷런]
- 파이썬 머신러닝 라이브러리 중 가장 많이 사용됨(근래 사이킷런 외에 텐서플로, 케라스 등 딥러닝 라이브러리도 많이 사용됨... 근데 케라스가 이제 텐서플로에 들어갔다 그랬던거 같음)
- 쉽고 파이썬스러운 API 제공
- 다양한 알고리즘과 편리한 프레임워크, API 제공
 - 프레임워크: 프로그램을 개발하기 위해 사용되는 틀을 제공하는 프로그램 (https://velog.io/@suss-lee/%ED%94%84%EB%A0%88%EC%9E%84%EC%9B%8C%ED%81%ACFramework%EB%9E%80-%EB%AC%B4%EC%97%87%EC%9D%B8%EA%B0%80)
 - API: application programming interface, 프로그램과 프로그램을 연결시키는 그런 매개체
- 그냥 머신러닝 분야에선 아주 많이 사용된다~

# 📌2.2 첫 번째 머신러닝 만들어 보기 - 붓꽃 품종 예측하기

**[지도학습]**  
  : 학습을 위해 피처와 결정값(Label)으로 모델을 학습한 뒤, 별도의 테스트 데이터에서 미지의 레이블을 예측.  
   -> 비지도학습과의 제일 큰 차이는 **명확한 정답(=레이블)이 주어진 데이터 세트를 사용**한다는 것!

**[분류]**  
  : 지도학습 방법 중 하나로, 반응변수가 범주형일 때 사용.(연속형일 땐 회귀)  


In [2]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

[sklearn 주요 모듈 세트]  
- 기본적으로 sklearn으로 모듈명 시작.
- `sklearn.datasets`
 - sklearn가 제공하는 데이터 세트 생성
 - 아이리스 데이터는 load_iris로 불러오기 가능
- `sklearn.tree`
 - 트리 기반 머신러닝 알고리즘 구현 클래스 모임
- `sklearn.model_selection`
 - 학습/검증데이터 split 또는 최적 하이퍼 파라미터 튜닝 등을 위한 모듈 모임


In [3]:
import pandas as pd

#붓꽃 데이터 세트를 로딩합니다.
iris = load_iris()

#iris.data는 iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있습니다.
iris_data = iris.data

#iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있습니다.
iris_label = iris.target
print('iris target 값: ', iris_label)
print('iris target 명: ', iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 DataFrame으로 변환합니다.
#iris.feature_names는 이름 그대로 iris 데이터의 칼럼명을 가지고 있음.
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)
#아래 코드에서 기존 iris_df엔 없던 label 칼럼을 추가해줌.
iris_df['label'] = iris.target
iris_df.head(3)

iris target 값:  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target 명:  ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [4]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,
                                                    test_size = 0.2, random_state = 11)

In [5]:
#DecisionTreeClassifier 객체 생성
dt_clf = DecisionTreeClassifier(random_state = 11)

#학습 수행
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=11)

In [6]:
#학습이 완료된 DecisionTreeClassifier 객체에서 테스트 데이터 세트로 예측 수행
pred = dt_clf.predict(X_test)

In [7]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.933333


- `train_test_split(X, y, test_size, random_state)` -> 학습용/테스트용 데이터 분리, 아래 2-4에서 더 자세히 다룸.

- 결정트리 학습/테스트
 - `dt = DecisionTreeClassifier(random_state = 11)`과 같이 특정 변수에 결정트리 객체를 생성(랜덤값 지정 필수 아님)
 - `dt.fit(X_train, y_train)` 처럼 위에서 객체 지정한 변수에 fit으로 train 피처, train 레이블 지정해서 학습 수행
 - `dt.predict(X_test)` -> 학습된 결정트리에 X_test 피처를 통해 테스트 레이블 예측
 - `accuracy_score(y_test, pred)`로 y_test, pred 사이의 일치하는 값의 수를 통해 정확도 측정

**[분류 프로세스 정리]**
1. 데이터 세트 분리: 데이터를 학습/테스트용으로 분리
2. 모델 학습: fit 메소드와 학습용 데이터로 모델 학습
3. 예측 수행: 학습된 모델을 통해 학습용 데이터의 레이블 예측
4. 예측된 결과값과 실제값을 비교해 모델 성능 평가

# 📌2.3 사이킷런의 기반 프레임워크 익히기


In [8]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))

<class 'sklearn.utils._bunch.Bunch'>


In [9]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들: ', keys)

붓꽃 데이터 세트의 키들:  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [10]:
print('\n feature_names의 type: ', type(iris_data.feature_names))
print(' feature_names의 shape: ', len(iris_data.feature_names))
print(iris_data.feature_names)

print('\n target_names의 type: ', type(iris_data.target_names))
print(' target_names의 shape: ', len(iris_data.target_names))
print(iris_data.target_names)

print('\n data의 type: ', type(iris_data.data))
print(' data의 shape: ', iris_data.data.shape)
print(iris_data['data'])

print('\n target의 type: ', type(iris_data.target))
print(' target의 shape: ', iris_data.target.shape)
print(iris_data.target)


 feature_names의 type:  <class 'list'>
 feature_names의 shape:  4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names의 type:  <class 'numpy.ndarray'>
 target_names의 shape:  3
['setosa' 'versicolor' 'virginica']

 data의 type:  <class 'numpy.ndarray'>
 data의 shape:  (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.

[Estimator, fit, predict]
- Estimator
 - 지도학습의 모든 알고리즘을 구현한 클래스를 통칭
 - 회귀 클래스: Regressor, 분류 클래스: Classifier
- fit
 - 모델을 학습시킬 때 사용
- predict
 - 학습될 모델에게 레이블 예측을 시킬 때 사용
- 비지도학습의 fit(), transform(), fit_transform
 - fit -> 입력 데이터의 차원 변환, 클러스터링, 피처 추출 등의 작업을 위해 사전 구조 맞춤
 - transform -> fit으로 맞춘 바를 기준으로 해서 데이터 변환 작업
 - fit_transform -> 그냥 이름 그대로 fit, transform을 한방에 적용해줌

[내장된 예제 데이터 세트]  
: 사이킷런에 내장된 데이터세트는 일반적으로 딕셔너리 형태로 data, target, target_name, feature_name, DESCR 의 키들로 구성됨.
- data: 피처의 데이터 세트
- target: 반응변수 데이터 세트
- target_names: 개별 레이블의 이름(ex. setosa, virginica...)
- feature_names: 피처의 이름(ex. petal_length, petal_width...)
- DESCR: 데이터세트와 각 피처에 대한 설명
  
내장된 데이터 세트 목록

| API 명 | 설명 |
| ------------ | ------------- |
| datasets.load_boston() | 회귀, 보스턴 집값예측 |
| datasets.load_breast_cancer() | 분류, 위스콘신 유방암 악성 음성 예측|  
|datasets.load_diabetes()| 회귀, 당뇨 데이터|
|datasets.load_digits()| 분류, 0~9 숫자 이미지 픽셀 데이터|
|datasets.load_iris()| 분류, 붓꽃 데이터 |

이런 애들 외에도 fetch계열의 웹 다운로드 데이터도 있고 군집화용 blobs도 있다~

# 📌2.4 Model Selection 모듈 소개

In [11]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris = load_iris()
dt_clf = DecisionTreeClassifier()
train_data = iris.data
train_label = iris.target
dt_clf.fit(train_data, train_label)

#학습 데이터 세트로 예측 수행
pred = dt_clf.predict(train_data)
print('예측 정확도: ', accuracy_score(train_label, pred))

예측 정확도:  1.0


In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf = DecisionTreeClassifier()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size = 0.3, random_state = 121)

In [14]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

예측 정확도: 0.9556


In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state = 156)

#5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성
kfold = KFold(n_splits = 5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기: ', features.shape[0])

붓꽃 데이터 세트 크기:  150


In [16]:
n_iter = 0

#KFold 객체의 split()를 호출하면 폴드 별 학습용, 검증용 테스트의 로우 인덱스를 array로 반환
for train_index, test_index in kfold.split(features):
  #kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter +=1
  #반복 시마다 정확도 측정
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n## 평균 검증 정확도: ', np.mean(cv_accuracy))


#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 교차 검증 정확도 :0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 교차 검증 정확도 :0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도:  0.9


In [17]:
import pandas as pd

iris = load_iris()
iris_df = pd.DataFrame(data=iris.data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [20]:
kfold = KFold(n_splits = 3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
  n_iter+=1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포: \n', label_train.value_counts())
  print('검증 레이블 데이터 분포: \n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포: 
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    50
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포: 
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 1    50
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포: 
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 2    50
Name: label, dtype: int64


In [21]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits = 3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter+=1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print('## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포: \n', label_train.value_counts())
  print('검증 레이블 데이터 분포: \n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포: 
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    17
1    17
2    16
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포: 
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    17
2    17
1    16
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포: 
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 1    17
2    17
0    16
Name: label, dtype: int64


In [22]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits = 3)
n_iter = 0
cv_accuracy = []

#StratifiedKFold의 split() 호출시 반드시 레이블 데이터 세트도 추가 입력 필요
for train_index, test_index in skfold.split(features, label):
  #kfold.split()으로 반환된 인덱스를 이용해 학습용, 검증용 테스트 데이터 추출
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]
  #학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)

  #반복 시마다 정확도 측정
  n_iter +=1
  accuracy = np.round(accuracy_score(y_test, pred), 4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
  print('#{0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

#교차 검증별 정확도 및 평균 정확도 계산
print('\n## 교차 검증별 정확도: ', np.round(cv_accuracy, 4))
print('\n## 평균 검증 정확도: ', np.mean(cv_accuracy))


#1 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 :0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도:  [0.98 0.94 0.98]

## 평균 검증 정확도:  0.9666666666666667


In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state = 156)

data = iris_data.data
label = iris_data.target

#성능 지표는 정확도(accuracy), 교차 검증 세트는 3개
scores = cross_val_score(dt_clf, data, label, scoring = 'accuracy', cv = 3)
print('교차 검증별 정확도: ', np.round(scores, 4))
print('평균 검증 정확도: ', np.round(np.mean(scores), 4))

교차 검증별 정확도:  [0.98 0.94 0.98]
평균 검증 정확도:  0.9667


In [26]:
grid_parameters = {'max_depth': [1, 2, 3],
                   'min_samples_split': [2, 3]
                   }

In [27]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

#데이터를 로딩하고 학습 데이터와 테스트 데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                    test_size = 0.2, random_state = 121)
dtree = DecisionTreeClassifier()

### 파라미터를 딕셔너리 형태로 설정
parameters = {'max_depth': [1, 2, 3], 'min_samples_split':[2, 3]}

In [28]:
import pandas as pd
#param_grid의 하이퍼 파라미터를 3개의train, test, set fold로 나누어 테스트 수행 설정
###refit = True 가 디폴트임. True이면 가장 좋은 파라미터 설정으로 재학습시킴
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv = 3, refit = True)

#붓꽃 학습 데이터로 param_grid의 하이퍼 파라미터를 순차적으로 학습/평가
grid_dtree.fit(X_train, y_train)

#GridSearchCV 결과를 추출해 DataFrame으로 변환
score_df = pd.DataFrame(grid_dtree.cv_results_)
score_df[['params', 'mean_test_score', 'rank_test_score',
          'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [29]:
print('GridSearchCV 최적 파라미터: ', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터:  {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750


In [30]:
#GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_

#GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도: 0.9667


[`train_test_split(X, y, test_size, random_state)`]  
 -> 학습용/테스트용 데이터 분리
- 학습용 데이터와 테스트용 데이터를 분리해서 사용하지 않으면 분류의 경우 자신이 학습한 데이터로(= 자신이 답을 다 아는 상태임) 테스트를 진행하면 당연히 정확도가 1이 나오게 된다. 따라서 분리가 필수적!
- X: 피처 데이터 세트
- y: 레이블 데이터 세트
- test_size: 전체 데이터에서 test용으로 사용할 데이터의 비율
- train_size: 전체 데이터에서 train용으로 사용할 데이터의 비율, 그렇지만 test_size가 더 많이 사용되어서 딱히 쓸일은 없음
- random_state: 그냥 random seed 지정, 항상 같은 랜덤값이 나오게 하기 위해 사용.
- shuffle = True: True가 디폴트, 랜덤으로 섞어서 split함. 근데 이제 진짜 제대로 분석하려면 당연히 셔플된 상태로 나눠야함.
- 최종적으로 반환하는건 순서대로 학습용 피처, 테스트용 피처, 학습용 레이블, 테스트용 레이블!
- 그래서 아래의 구문이 그냥 거의 디폴트 값으로 사용됨  
  `X_train, X_test, y_train, y_test = train_test_split(X, y, test_size, random_state)`

[교차 검증]  
: 고정된 학습/테스트 데이터만 이용하면 해당 데이터에 과적합된 모델을 얻을 수 있음  
-> 교차검증을 사용해서 다수의 학습 데이터, 검증 데이터 세트를 사용하여 과적합을 막는다!  
: 간단하게 말해서 학습 데이터 세트를 학습/검증 데이터 세트로 나누고, 검증 데이터 세트로 교차검증을 시행한 후에 테스트 데이터에 최종적으로 넣어 성능을 평가한다!

- K Fold 교차 검증
 - 가장 보편적으로 사용되는 교차 검증
 - 전체 데이터를 K개의 Fold로 나누고 그 중 하나를 검증, 나머지를 학습데이터로 사용해서 학습/검증 과정을 거침. -> 총 K번의 학습/검증 과정, 그리고 그 K번의 성능 평가 결과 평균을 낸다!
- Stratified K Fold
 - 레이블이 불균형할 때 사용하는 폴드 방식
 - 레이블이 불균형하다면 아무리 랜덤하게 데이터 split을 해도 그 불균형한 비율이 반영되지 않을 수 있음.
 - 따라서 이러한 레이블 분포를 먼저 고려하고 해당 분포와 동일하게 학습과 검증 데이터 세트를 분배하는 Fold 방식
 - 일반적으로 분류 알고리즘에선 KFold보다 Stratified KFold를 사용하는 것이 알맞음
 - 어차피 회귀알고리즘은 결정값이 연속형이기 때문에 분포를 맞출수 없기 때문에 Stratified가 사용 불가능함
- cross_val_score
 - `cross_val_score(estimator, X, y = None, cv = None, n_jobs = 1, verbose = 0, fit_params = None, pre_dispatch = '2*n_jobs')`
 - estimator: 분류 또는 회귀 알고리즘
 - X, y: 피처 데이터, 레이블 데이터
 - scoring: 예측 성능 평가 지표
 - cv: 교차 검증 폴드 수
 - estimator= 분류 -> Stratified KFold, 회귀 -> KFold
 - 교차검증 평가 결과값을 cv길이의 배열로 반환
 - 이미 해당 API 내에서 학습, 예측, 평가를 전부 해주기 때문에 매우 간단함.
 - 비슷한 API로 `cross_validate()`는 여러개의 평가 지표를 반환할 수 있다.

- GridSearchCV  
  : 하이퍼 파라미터 튜닝을 통해 알고리즘 성능 개선을 하는 API
  - 간단하게 후보군으로 지정된 모든 하이퍼 파라미터 세트를 번갈에 입력하며 학습시키고 그 결과를 비교
  - 시간이 오래 걸리는 게 단점
  - 후보군에 하이퍼 파라미터 세트가 총 a개이고 cv를 b로 지정하면 총 a*b회의 학습/평가를 진행해야함.
  - param_grid: 딕셔너리 형태로 지정한 하이퍼 파라미터 후보군을 넣음
  - refit: 디폴트는 True, 최적의 하이퍼 파라미터를 찾으면 estimator 객체를 해당 하이퍼 파라미터로 재학습(refit)시킴
  - 보통의 머신러닝 객체들과 같이 fit()을 수행하고, 최고 성능의 하이퍼 파라미터는 best_params에, 그때의 평가 결과는 best_score_ 속성에 저장됨
